"""SimpleVectorlessMixin - BM25 retrieval + procedural badges for simple RAG agents.

Use as the FIRST parent in the MRO:

    class Agent(SimpleVectorlessMixin, SimpleRAGMixin, BaseRAGAgent):
        _AGENT_FILE = __file__

Provides procedural banners (Verified/AI Commentary/Unverified) instead of
claim-level reliability analysis.
"""

from .vectorless_mixin import VectorlessMixin

_BANNER_STYLE = 'padding:8px 12px;margin:6px 0;border-radius:4px;font-size:0.9em;'

_OFF_TOPIC_PHRASES = [
    "outside my scope", "outside the scope", "outside my area",
    "beyond my scope", "not within my scope", "outside my expertise",
    "i don't have information about that",
]


def _banner_verified(detail=""):
    text = detail or "This content is generated directly from the knowledge base (no AI involved)."
    return (
        f'<div style="background-color:#d4edda;border-left:4px solid #28a745;{_BANNER_STYLE}">'
        f'\U0001F7E2 <strong>Verified data</strong> \u2014 {text}'
        '</div>\n\n'
    )


def _banner_database(detail=""):
    text = detail or "The response below is generated by the AI model based on the knowledge base."
    return (
        f'<div style="background-color:#fff3cd;border-left:4px solid #ffc107;{_BANNER_STYLE}">'
        f'\U0001F7E1 <strong>AI Commentary</strong> \u2014 {text}'
        '</div>\n\n'
    )


def _banner_unverified(detail=""):
    text = detail or "This is outside the scope of the knowledge base."
    return (
        f'<div style="background-color:#f8d7da;border-left:4px solid #dc3545;{_BANNER_STYLE}">'
        f'\U0001F534 <strong>Unverified</strong> \u2014 {text}'
        '</div>\n\n'
    )


def _is_off_topic(text):
    text_lower = text.lower()
    return any(p in text_lower for p in _OFF_TOPIC_PHRASES)


class SimpleVectorlessMixin(VectorlessMixin):
    """Vectorless mixin for simple RAG agents with procedural badges.

    Banner logic:
    - Context retrieved + on-topic response -> AI Commentary (yellow)
    - No context but on-topic response (answered from prompt) -> AI Commentary (yellow)
    - Off-topic response -> Unverified (red)
    """

    _skip_claim_classification = True

    def chat(self, user_message: str, history: list = None, **kwargs) -> str:
        # If config overrode to content-based, delegate to SimpleRAGMixin
        if not getattr(self, '_skip_claim_classification', True):
            from .rag_mixin import SimpleRAGMixin
            return SimpleRAGMixin.chat(self, user_message, history, **kwargs)

        transparency = kwargs.get('transparency_override') or self._transparency
        model = kwargs.get('model_override') or self.model
        prompt_level = kwargs.get('prompt_level_override') or self._prompt_level

        if not self._chromadb_initialized:
            self._init_chromadb()

        context = self._retrieve_context(user_message)

        system_with_context = self._build_system_prompt()
        if context:
            system_with_context += f"\n\nRelevant context from the knowledge base:\n{context}"

        messages = [{"role": "system", "content": system_with_context}]
        if history:
            messages.extend(history)
        messages.append({"role": "user", "content": user_message})

        response = self.client.chat.complete(model=model, messages=messages)
        llm_content = response.choices[0].message.content

        # Procedural banner (Crystal box only)
        if transparency in ("crystal_box", "scaffolded"):
            if _is_off_topic(llm_content):
                llm_content = _banner_unverified() + llm_content
            else:
                llm_content = _banner_database() + llm_content

        # Save to query history
        self._query_history.append({
            'question': user_message,
            'response_length': len(llm_content),
        })

        return llm_content

    async def chat_stream(self, user_message: str, history: list = None, **kwargs):
        # If config overrode to content-based, delegate to SimpleRAGMixin
        if not getattr(self, '_skip_claim_classification', True):
            from .rag_mixin import SimpleRAGMixin
            async for item in SimpleRAGMixin.chat_stream(self, user_message, history, **kwargs):
                yield item
            return

        transparency = kwargs.get('transparency_override') or self._transparency
        model = kwargs.get('model_override') or self.model
        prompt_level = kwargs.get('prompt_level_override') or self._prompt_level

        if not self._chromadb_initialized:
            yield ("status", "Loading knowledge base...")
            self._init_chromadb()

        yield ("status", "Thinking...")

        context = self._retrieve_context(user_message)

        system_with_context = self._build_system_prompt()
        if context:
            system_with_context += f"\n\nRelevant context from the knowledge base:\n{context}"

        messages = [{"role": "system", "content": system_with_context}]
        if history:
            messages.extend(history)
        messages.append({"role": "user", "content": user_message})

        # Start with AI Commentary banner (most responses are on-topic)
        if transparency in ("crystal_box", "scaffolded"):
            yield ("procedural_banner", _banner_database())

        # Stream LLM response
        full_response = ""
        async for chunk in await self.client.chat.stream_async(model=model, messages=messages):
            if chunk.data.choices[0].delta.content:
                full_response += chunk.data.choices[0].delta.content
                yield chunk.data.choices[0].delta.content

        # If off-topic, replace the banner
        if transparency in ("crystal_box", "scaffolded") and _is_off_topic(full_response):
            yield ("replace", _banner_unverified() + full_response)

        # Save to query history
        self._query_history.append({
            'question': user_message,
            'response_length': len(full_response),
        })
