"""
Anatomy Explorer — LTI 1.1 Tool

Clickable 2D diagrams of the human body (muscles and bones, anterior and
posterior views). Students explore structures and take practice quizzes:
"click the structure named X" or "name the highlighted structure".
Teachers choose per course which systems, regions and structures are in
play, configure the quiz and add notes per structure. Practice only: no
results are stored. No LLM — everything runs client-side.

Diagrams are generated by tools/build_svgs.py from open-licensed art
(OpenStax / Wikimedia Commons, see static/info.html).

Configuration (web/.env):
    ANATOMY_LTI_KEY=anatomy_uma
    ANATOMY_LTI_SECRET=<shared_secret>

Moodle setup:
    Tool URL: https://gloria.uma.es/lti/anatomy
"""

import json
import os
from pathlib import Path

from fastapi import APIRouter, Request, HTTPException
from fastapi.responses import FileResponse, HTMLResponse, RedirectResponse

from UltiR.lti_common import (
    LTISessionStore, is_instructor, lti_launch, lti_test_launch,
)

router = APIRouter(tags=["lti_anatomy"])

_APP_DIR = Path(__file__).parent
_STATIC_DIR = _APP_DIR / "static"
_DATA_DIR = _APP_DIR / "data"
_DATA_DIR.mkdir(exist_ok=True)

LTI_KEY = os.environ.get("ANATOMY_LTI_KEY", "anatomy_uma")
LTI_SECRET = os.environ.get("ANATOMY_LTI_SECRET", "change_this_secret_in_env")

sessions = LTISessionStore()

CATALOG = json.loads((_APP_DIR / "catalog.json").read_text(encoding="utf-8"))
_STRUCTURE_IDS = [s["id"] for s in CATALOG["structures"]]
_SYSTEM_IDS = [s["id"] for s in CATALOG["systems"]]
_REGION_IDS = [r["id"] for r in CATALOG["regions"]]
_QUESTION_TYPES = ["click", "name"]

# Only these files are served as assets (no path traversal possible)
_ASSETS = {
    f"{sub}/{p.name}": p
    for sub, pattern in (("svg", "*.svg"), ("js", "*.js"))
    for p in (_STATIC_DIR / sub).glob(pattern)
}
_MEDIA_TYPES = {".svg": "image/svg+xml", ".js": "text/javascript"}

DEFAULT_CONFIG = {
    "systems": list(_SYSTEM_IDS),
    "regions": list(_REGION_IDS),
    "disabled": [],
    "quiz": {
        "num_questions": 10,
        "types": list(_QUESTION_TYPES),
        "side_specific": False,
        "timer_enabled": False,
        "timer_mode": "question",
        "timer_seconds": 30,
    },
    "notes": {},
}


# ── Data helpers ──────────────────────────────────────────────────────────────

def _course_path(course_id: str) -> Path:
    safe = "".join(c for c in course_id if c.isalnum() or c in "-_")[:64] or "default"
    return _DATA_DIR / f"{safe}.json"


def _load_config(course_id: str) -> dict:
    config = json.loads(json.dumps(DEFAULT_CONFIG))
    path = _course_path(course_id)
    if path.exists():
        saved = json.loads(path.read_text(encoding="utf-8"))
        config.update({k: v for k, v in saved.items() if k in config and k != "quiz"})
        config["quiz"].update(saved.get("quiz", {}))
    return config


def _save_config(course_id: str, config: dict):
    _course_path(course_id).write_text(
        json.dumps(config, indent=2, ensure_ascii=False), encoding="utf-8"
    )


def _validate_config(body: dict) -> dict:
    """Return a clean config built from untrusted input, or raise 400."""
    if not isinstance(body, dict):
        raise HTTPException(400, "Configuración inválida")

    def id_list(key, allowed):
        value = body.get(key, DEFAULT_CONFIG[key])
        if not isinstance(value, list) or not all(isinstance(v, str) and v in allowed for v in value):
            raise HTTPException(400, f"Valor inválido en '{key}'")
        return [v for v in allowed if v in value]

    systems = id_list("systems", _SYSTEM_IDS)
    regions = id_list("regions", _REGION_IDS)
    disabled = id_list("disabled", _STRUCTURE_IDS)
    if not systems or not regions:
        raise HTTPException(400, "Activa al menos un sistema y una región")

    quiz_in = body.get("quiz", {})
    if not isinstance(quiz_in, dict):
        raise HTTPException(400, "Configuración del test inválida")
    quiz = dict(DEFAULT_CONFIG["quiz"])
    try:
        quiz["num_questions"] = int(quiz_in.get("num_questions", quiz["num_questions"]))
        quiz["timer_seconds"] = int(quiz_in.get("timer_seconds", quiz["timer_seconds"]))
    except (TypeError, ValueError):
        raise HTTPException(400, "Número de preguntas o tiempo inválido")
    if not 1 <= quiz["num_questions"] <= 50:
        raise HTTPException(400, "El número de preguntas debe estar entre 1 y 50")
    if not 5 <= quiz["timer_seconds"] <= 3600:
        raise HTTPException(400, "El tiempo debe estar entre 5 y 3600 segundos")
    types = quiz_in.get("types", quiz["types"])
    if not isinstance(types, list) or not types or not all(t in _QUESTION_TYPES for t in types):
        raise HTTPException(400, "Elige al menos un tipo de pregunta")
    quiz["types"] = [t for t in _QUESTION_TYPES if t in types]
    quiz["side_specific"] = bool(quiz_in.get("side_specific", False))
    quiz["timer_enabled"] = bool(quiz_in.get("timer_enabled", False))
    quiz["timer_mode"] = "test" if quiz_in.get("timer_mode") == "test" else "question"

    notes_in = body.get("notes", {})
    if not isinstance(notes_in, dict):
        raise HTTPException(400, "Notas inválidas")
    notes = {}
    for sid, text in notes_in.items():
        if sid not in _STRUCTURE_IDS or not isinstance(text, str):
            raise HTTPException(400, "Notas inválidas")
        text = text.strip()[:2000]
        if text:
            notes[sid] = text

    return {"systems": systems, "regions": regions, "disabled": disabled, "quiz": quiz, "notes": notes}


# ── LTI Launch ────────────────────────────────────────────────────────────────

@router.get("/lti/anatomy")
async def anatomy_get():
    return RedirectResponse("/lti/anatomy/info", status_code=303)


@router.post("/lti/anatomy")
async def anatomy_launch(request: Request):
    return await lti_launch(
        request, LTI_KEY, LTI_SECRET, sessions,
        redirect_instructor="/lti/anatomy/viewer",
        redirect_learner="/lti/anatomy/viewer",
    )


@router.get("/lti/anatomy/test")
async def anatomy_test(role: str = "instructor"):
    return await lti_test_launch(
        sessions,
        redirect_instructor="/lti/anatomy/viewer",
        redirect_learner="/lti/anatomy/viewer",
        role=role,
    )


# ── Pages and assets ──────────────────────────────────────────────────────────

@router.get("/lti/anatomy/info")
async def anatomy_info():
    return HTMLResponse((_STATIC_DIR / "info.html").read_text(encoding="utf-8"))


@router.get("/lti/anatomy/viewer")
async def anatomy_viewer(request: Request):
    sessions.require(request)
    return HTMLResponse((_STATIC_DIR / "viewer.html").read_text(encoding="utf-8"))


@router.get("/lti/anatomy/assets/{kind}/{name}")
async def anatomy_asset(kind: str, name: str):
    path = _ASSETS.get(f"{kind}/{name}")
    if not path:
        raise HTTPException(404, "Not found")
    return FileResponse(path, media_type=_MEDIA_TYPES[path.suffix],
                        headers={"Cache-Control": "public, max-age=3600"})


# ── API ───────────────────────────────────────────────────────────────────────

@router.get("/lti/anatomy/api/session")
async def anatomy_session(request: Request):
    session = sessions.require(request)
    return {
        "name": session["name"],
        "role": session["role"],
        "course_id": session.get("course_id", "default"),
        "course_name": session.get("course_name", ""),
        "is_instructor": is_instructor(session),
    }


@router.get("/lti/anatomy/api/catalog")
async def anatomy_catalog(request: Request):
    sessions.require(request)
    return CATALOG


@router.get("/lti/anatomy/api/config")
async def anatomy_config(request: Request):
    session = sessions.require(request)
    return _load_config(session.get("course_id", "default"))


@router.put("/lti/anatomy/api/config")
async def anatomy_config_save(request: Request):
    session = sessions.require(request)
    if not is_instructor(session):
        raise HTTPException(403, "Solo docentes pueden cambiar la configuración")
    config = _validate_config(await request.json())
    _save_config(session.get("course_id", "default"), config)
    return {"ok": True, "config": config}
